[package]
name = "qualification"
version = "0.1.0"
authors = ["SeongChan Lee <foriequal@gmail.com>"]

[dependencies]

[[bin]]
name = "A"
path = "A.rs"

[[bin]]
name = "B"
path = "B.rs"

[[bin]]
name = "C"
path = "C.rs"

[[bin]]
name = "D"
path = "D.rs"
